mkdir -p "$HOME/.jriver/Media Center $MC_MAJOR_VERSION"
cp -a -n "$APPDIR/usr/lib/jriver/Media Center $MC_MAJOR_VERSION/Skins" "$HOME/.jriver/Media Center $MC_MAJOR_VERSION"
cp -a -n "$APPDIR/usr/lib/jriver/Media Center $MC_MAJOR_VERSION/Data" "$HOME/.jriver/Media Center $MC_MAJOR_VERSION"
cp -a -n "$APPDIR/usr/lib/jriver/Media Center $MC_MAJOR_VERSION/Plugins" "$HOME/.jriver/Media Center $MC_MAJOR_VERSION"
cp -a -n "$APPDIR/usr/lib/jriver/Media Center $MC_MAJOR_VERSION/Visualizations" "$HOME/.jriver/Media Center $MC_MAJOR_VERSION"
"$APPDIR/usr/bin/mediacenter$MC_MAJOR_VERSION"