name: Build

on:
  branches:
    - main

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Build AppImage
        uses: AppImageCrafters/build-appimage@master
        with:
          recipe: "./com.jriver.mediacenter32.appimage.yml"
        env:
          UPDATE_INFO: gh-releases-zsync|AppImageCrafters|com.jriver.mediacenter32|latest|*x86_64.AppImage.zsync